query ($course_id: ID, $after: String = null) {
  course(id: $course_id) {
    modulesConnection(first: 10, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        _id
        updatedAt
        name
        moduleItems {
          _id
          updatedAt
          content {
            ... on File {
              type: __typename
              _id
              updatedAt
              name: displayName
              url
            }
            ... on ExternalUrl {
              type: __typename
              _id
              updatedAt
              name: title
              url
            }
          }
        }
      }
    }
  }
}
